package com.seventhlayer.kokedera.icons

/**
 * Single source of truth for all icon mappings, shared by
 * [KokederaFileIconProvider] and [KokederaDirectoryIconProvider].
 * Kept in sync with the VS Code and Zed extensions.
 */
object KokederaIconMappings {

    /**
     * Resolves the icon name for a file, or null if no mapping exists.
     * [fullPath] enables path-aware mappings (e.g. GitHub workflow files).
     */
    fun fileIconName(fileName: String, extension: String?, fullPath: String? = null): String? {
        if (fullPath != null && isGithubWorkflow(fullPath, fileName)) return "github-actions"

        // Check exact filename first
        FILE_NAMES[fileName]?.let { return it }

        // Check compound extensions (e.g., d.ts, test.js)
        val lowerName = fileName.lowercase()
        for ((suffix, iconName) in COMPOUND_EXTENSIONS) {
            if (lowerName.endsWith(suffix)) return iconName
        }

        // Check file extension
        return extension?.lowercase()?.let { FILE_EXTENSIONS[it] }
    }

    fun folderIconName(folderName: String): String? = FOLDER_NAMES[folderName.lowercase()]

    private fun isGithubWorkflow(fullPath: String, fileName: String): Boolean {
        if (!fileName.endsWith(".yml") && !fileName.endsWith(".yaml")) return false
        // VirtualFile paths are always '/'-separated, on all platforms
        return fullPath.contains("/.github/workflows/")
    }

    val COMPOUND_EXTENSIONS = listOf(
        ".d.ts" to "ts-def",
        ".d.mts" to "ts-def",
        ".d.cts" to "ts-def",
        ".test.js" to "test",
        ".test.ts" to "test",
        ".test.jsx" to "test",
        ".test.tsx" to "test",
        ".spec.js" to "test",
        ".spec.ts" to "test",
        ".spec.jsx" to "test",
        ".spec.tsx" to "test",
        ".stories.js" to "storybook",
        ".stories.ts" to "storybook",
        ".stories.jsx" to "storybook",
        ".stories.tsx" to "storybook",
        ".env.local" to "env-local",
        ".env.development" to "env-local",
        ".env.production" to "env-local",
        ".env.staging" to "env-local",
        ".env.test" to "env-local",
    )

    val FILE_NAMES = mapOf(
        // Package managers
        "package.json" to "package",
        "package-lock.json" to "lockfile",
        "yarn.lock" to "yarn",
        "pnpm-lock.yaml" to "pnpm",
        "Gemfile.lock" to "lockfile",
        "Cargo.lock" to "lockfile",
        "poetry.lock" to "lockfile",
        "composer.lock" to "lockfile",
        "Pipfile.lock" to "lockfile",
        "bun.lockb" to "bun",
        "go.sum" to "lockfile",
        "flake.lock" to "lockfile",
        "deno.lock" to "deno",
        "Cargo.toml" to "package",
        "Gemfile" to "package",
        "Pipfile" to "package",
        "pyproject.toml" to "package",
        "setup.py" to "package",
        "setup.cfg" to "package",
        "composer.json" to "package",
        "go.mod" to "package",
        ".npmrc" to "package",
        ".yarnrc" to "yarn",
        "pnpm-workspace.yaml" to "pnpm",
        ".pnpmfile.cjs" to "pnpm",
        "project.godot" to "gdscript",
        "nim.cfg" to "nim",
        ".commitlintrc" to "json",
        ".commitlintrc.json" to "json",
        ".huskyrc" to "json",
        ".huskyrc.json" to "json",
        ".lintstagedrc" to "json",
        ".lintstagedrc.json" to "json",
        "commitlint.config.cjs" to "json",
        "commitlint.config.js" to "json",
        "commitlint.config.ts" to "json",
        "lint-staged.config.js" to "json",
        "lint-staged.config.mjs" to "json",
        "Taskfile.yaml" to "yaml",
        "Taskfile.yml" to "yaml",
        "app.yaml" to "yaml",
        "app.yml" to "yaml",
        "render.yaml" to "yaml",
        "serverless.yaml" to "yaml",
        "serverless.yml" to "yaml",
        "bun.toml" to "package",
        "bunfig.toml" to "bun",
        "Brewfile" to "package",

        // Git
        ".gitignore" to "gitignore",
        ".gitattributes" to "gitignore",
        ".gitmodules" to "gitignore",

        // Env
        ".env" to "env",
        ".env.example" to "env",
        ".env.sample" to "env",

        // Build tools
        "Makefile" to "make",
        "makefile" to "make",
        "GNUmakefile" to "make",
        "CMakeLists.txt" to "make",
        "Justfile" to "make",
        "justfile" to "make",

        // Docker
        "Dockerfile" to "docker",
        "dockerfile" to "docker",
        "Containerfile" to "docker",
        "Earthfile" to "docker",
        ".dockerignore" to "docker",
        ".containerignore" to "docker",
        "docker-compose.yml" to "docker-compose",
        "docker-compose.yaml" to "docker-compose",
        "compose.yml" to "docker-compose",
        "compose.yaml" to "docker-compose",

        // CI/CD
        "Jenkinsfile" to "jenkinsfile",
        ".gitlab-ci.yml" to "gitlab-ci",
        "nginx.conf" to "nginx",

        // Docs
        "LICENSE" to "license",
        "LICENSE.md" to "license",
        "LICENSE.txt" to "license",
        "LICENCE" to "license",
        "LICENCE.md" to "license",
        "LICENCE.txt" to "license",
        "COPYING" to "license",
        "README" to "readme",
        "README.md" to "readme",
        "README.txt" to "readme",
        "README.rst" to "readme",
        "CHANGELOG" to "changelog",
        "CHANGELOG.md" to "changelog",
        "CHANGELOG.txt" to "changelog",
        "CHANGES" to "changelog",
        "CHANGES.md" to "changelog",
        "HISTORY" to "changelog",
        "HISTORY.md" to "changelog",
        "RELEASE_NOTES.md" to "changelog",

        // Linters
        ".eslintrc" to "eslint",
        ".eslintrc.js" to "eslint",
        ".eslintrc.cjs" to "eslint",
        ".eslintrc.json" to "eslint",
        ".eslintrc.yml" to "eslint",
        ".eslintrc.yaml" to "eslint",
        "eslint.config.js" to "eslint",
        "eslint.config.mjs" to "eslint",
        "eslint.config.cjs" to "eslint",
        "eslint.config.ts" to "eslint",
        "biome.json" to "eslint",
        "biome.jsonc" to "eslint",
        ".oxlintrc.json" to "eslint",
        ".prettierrc" to "prettier",
        ".prettierrc.js" to "prettier",
        ".prettierrc.cjs" to "prettier",
        ".prettierrc.json" to "prettier",
        ".prettierrc.yml" to "prettier",
        ".prettierrc.yaml" to "prettier",
        ".prettierrc.toml" to "prettier",
        "prettier.config.js" to "prettier",
        "prettier.config.cjs" to "prettier",
        "prettier.config.mjs" to "prettier",
        ".prettierignore" to "prettier",
        ".editorconfig" to "editorconfig",

        // Bundlers & frameworks
        "webpack.config.js" to "webpack",
        "webpack.config.ts" to "webpack",
        "webpack.config.cjs" to "webpack",
        "webpack.config.mjs" to "webpack",
        "vite.config.js" to "vite",
        "vite.config.ts" to "vite",
        "vite.config.mjs" to "vite",
        "vite.config.mts" to "vite",
        "babel.config.js" to "babel",
        "babel.config.cjs" to "babel",
        "babel.config.mjs" to "babel",
        "babel.config.json" to "babel",
        ".babelrc" to "babel",
        ".babelrc.json" to "babel",
        "next.config.js" to "nextjs",
        "next.config.mjs" to "nextjs",
        "next.config.ts" to "nextjs",
        "tailwind.config.js" to "tailwind",
        "tailwind.config.ts" to "tailwind",
        "tailwind.config.cjs" to "tailwind",
        "tailwind.config.mjs" to "tailwind",
        ".npmignore" to "npmignore",

        // TypeScript configs
        "tsconfig.json" to "typescript",
        "tsconfig.build.json" to "typescript",
        "tsconfig.app.json" to "typescript",
        "tsconfig.node.json" to "typescript",

        // Framework configs
        "angular.json" to "angular",
        ".angular-cli.json" to "angular",
        "svelte.config.js" to "svelte",
        "svelte.config.ts" to "svelte",
        "astro.config.mjs" to "astro",
        "astro.config.ts" to "astro",
        "nuxt.config.js" to "vue",
        "nuxt.config.ts" to "vue",
        "vue.config.js" to "vue",

        // Gradle / Maven
        "gradlew" to "shell",
        "gradlew.bat" to "shell",
        "build.gradle" to "java",
        "settings.gradle" to "java",
        "build.gradle.kts" to "kotlin",
        "settings.gradle.kts" to "kotlin",
        "gradle.properties" to "toml",
        "gradle-wrapper.properties" to "toml",
        "pom.xml" to "xml",
        "mvnw" to "shell",
        "mvnw.cmd" to "shell",

        // Spring Boot
        "application.yml" to "yaml",
        "application.yaml" to "yaml",
        "application.properties" to "toml",
        "application-dev.yml" to "yaml",
        "application-dev.yaml" to "yaml",
        "application-prod.yml" to "yaml",
        "application-prod.yaml" to "yaml",
        "bootstrap.yml" to "yaml",
        "bootstrap.yaml" to "yaml",

        // Misc
        "Procfile" to "shell",
        "flake.nix" to "nix",
        "schema.prisma" to "prisma",
        "Rakefile" to "ruby",
        "Vagrantfile" to "ruby",

        // CSS tools
        "postcss.config.js" to "css",
        "postcss.config.cjs" to "css",
        "postcss.config.mjs" to "css",
        "postcss.config.ts" to "css",

        // Test configs
        "jest.config.js" to "test",
        "jest.config.ts" to "test",
        "jest.config.mjs" to "test",
        "jest.config.cjs" to "test",
        "vitest.config.js" to "test",
        "vitest.config.ts" to "test",
        "vitest.config.mts" to "test",
        "cypress.config.js" to "test",
        "cypress.config.ts" to "test",
        "playwright.config.js" to "test",
        "playwright.config.ts" to "test",

        // DB
        "drizzle.config.ts" to "sql",
        "drizzle.config.js" to "sql",
        "knexfile.js" to "sql",
        "knexfile.ts" to "sql",

        // Deploy
        "vercel.json" to "json",
        "netlify.toml" to "toml",
        "wrangler.toml" to "toml",
        "fly.toml" to "toml",

        // Version managers & monorepo tools (synced with VS Code/Zed mappings)
        ".yarnrc.yml" to "yarn",
        "bun.lock" to "bun",
        ".nvmrc" to "node",
        ".node-version" to "node",
        ".python-version" to "python",
        ".ruby-version" to "ruby",
        ".tool-versions" to "json",
        "turbo.json" to "json",
        "lerna.json" to "json",
        "rush.json" to "json",
        "deno.json" to "deno",
        "deno.jsonc" to "deno",
        "renovate.json" to "json",
        ".renovaterc" to "json",
        ".renovaterc.json" to "json",
        "railway.toml" to "toml",

        // Task runners & framework configs (synced)
        "Gruntfile.js" to "javascript",
        "Gulpfile.js" to "javascript",
        "Gruntfile.ts" to "typescript",
        "Gulpfile.ts" to "typescript",
        "remix.config.js" to "javascript",
        "remix.config.ts" to "typescript",
        "gatsby-config.js" to "javascript",
        "gatsby-config.ts" to "typescript",

        // Style tooling (synced)
        ".postcssrc" to "css",
        ".postcssrc.json" to "css",
        ".postcssrc.yml" to "css",
        "stylelint.config.js" to "css",
        "stylelint.config.cjs" to "css",
        "stylelint.config.mjs" to "css",
        ".stylelintrc" to "css",
        ".stylelintrc.json" to "css",
        ".stylelintrc.yml" to "css",

        // Test setup (synced)
        "jest.setup.js" to "test",
        "jest.setup.ts" to "test",
        ".mocharc.yml" to "test",
        ".mocharc.json" to "test",

        // Kubernetes / Helm
        "kustomization.yaml" to "kubernetes",
        "kustomization.yml" to "kubernetes",
        "skaffold.yaml" to "kubernetes",
        "skaffold.yml" to "kubernetes",
        "helmfile.yaml" to "kubernetes",
        "helmfile.yml" to "kubernetes",
        "Chart.yaml" to "kubernetes",
        "Chart.lock" to "kubernetes",
        "values.yaml" to "kubernetes",

        // GitHub
        "action.yml" to "github-actions",
        "action.yaml" to "github-actions",
        "dependabot.yml" to "github-actions",
        "dependabot.yaml" to "github-actions",
        "CODEOWNERS" to "github-actions",
    )

    val FILE_EXTENSIONS = mapOf(
        // JavaScript / TypeScript
        "js" to "javascript",
        "mjs" to "javascript",
        "cjs" to "javascript",
        "coffee" to "javascript",
        "ts" to "typescript",
        "mts" to "typescript",
        "cts" to "typescript",
        "jsx" to "jsx",
        "tsx" to "jsx",

        // Web
        "html" to "html",
        "htm" to "html",
        "xhtml" to "html",
        "pug" to "html",
        "jade" to "html",
        "njk" to "html",
        "twig" to "html",
        "liquid" to "html",
        "jinja" to "html",
        "jinja2" to "html",
        "j2" to "html",
        "css" to "css",
        "pcss" to "css",
        "postcss" to "css",
        "scss" to "scss",
        "sass" to "scss",
        "less" to "less",
        "vue" to "vue",
        "svelte" to "svelte",
        "astro" to "astro",
        "hbs" to "handlebars",
        "handlebars" to "handlebars",
        "mustache" to "handlebars",
        "ejs" to "ejs",
        "svg" to "svg",

        // Data & Config
        "json" to "json",
        "jsonc" to "json",
        "json5" to "json",
        "jsonl" to "json",
        "geojson" to "json",
        "webmanifest" to "json",
        "yml" to "yaml",
        "yaml" to "yaml",
        "ini" to "yaml",
        "conf" to "yaml",
        "cfg" to "yaml",
        "properties" to "yaml",
        "toml" to "toml",
        "xml" to "xml",
        "xsl" to "xml",
        "xslt" to "xml",
        "xsd" to "xml",
        "plist" to "xml",
        "csproj" to "xml",
        "fsproj" to "xml",
        "vbproj" to "xml",
        "vcxproj" to "xml",
        "csv" to "csv",
        "tsv" to "csv",
        "iml" to "xml",
        "graphql" to "graphql",
        "gql" to "graphql",
        "proto" to "protobuf",
        "env" to "env",

        // Languages
        "py" to "python",
        "pyi" to "python",
        "pyw" to "python",
        "pyx" to "python",
        "rs" to "rust",
        "ron" to "rust",
        "go" to "go",
        "c" to "c",
        "h" to "c",
        "cpp" to "cpp",
        "cc" to "cpp",
        "cxx" to "cpp",
        "hpp" to "cpp",
        "hxx" to "cpp",
        "hh" to "cpp",
        "ino" to "cpp",
        "cs" to "csharp",
        "fs" to "csharp",
        "fsx" to "csharp",
        "java" to "java",
        "jar" to "java",
        "class" to "java",
        "jsp" to "java",
        "gradle" to "java",
        "groovy" to "java",
        "kt" to "kotlin",
        "kts" to "kotlin",
        "rb" to "ruby",
        "erb" to "ruby",
        "gemspec" to "ruby",
        "cr" to "ruby",
        "php" to "php",
        "phtml" to "php",
        "swift" to "swift",
        "dart" to "dart",
        "zig" to "zig",
        "ex" to "elixir",
        "exs" to "elixir",
        "eex" to "elixir",
        "heex" to "elixir",
        "erl" to "elixir",
        "hrl" to "elixir",
        "hs" to "haskell",
        "lhs" to "haskell",
        "elm" to "haskell",
        "ml" to "haskell",
        "mli" to "haskell",
        "scala" to "scala",
        "sc" to "scala",
        "sbt" to "scala",
        "lua" to "lua",
        "luau" to "lua",
        "r" to "r",
        "rmd" to "r",
        "jl" to "julia",
        "pl" to "perl",
        "pm" to "perl",
        "clj" to "clojure",
        "cljs" to "clojure",
        "cljc" to "clojure",
        "edn" to "clojure",
        "gleam" to "gleam",
        "nix" to "nix",
        "prisma" to "prisma",
        "wasm" to "wasm",
        "wat" to "wasm",
        "glsl" to "wasm",
        "hlsl" to "wasm",
        "wgsl" to "wasm",

        // Shell
        "sh" to "shell",
        "bash" to "shell",
        "zsh" to "shell",
        "fish" to "shell",
        "bat" to "shell",
        "cmd" to "shell",
        "ps1" to "powershell",
        "psm1" to "powershell",
        "psd1" to "powershell",

        // SQL
        "sql" to "sql",
        "sqlite" to "sql",
        "sqlite3" to "sql",
        "pgsql" to "sql",
        "mysql" to "sql",

        // DevOps
        "tf" to "terraform",
        "tfvars" to "terraform",
        "hcl" to "terraform",
        "tfstate" to "terraform",
        "dockerfile" to "docker",
        "dockerignore" to "docker",

        // Documents
        "md" to "markdown",
        "markdown" to "markdown",
        "mdx" to "mdx",
        "txt" to "txt",
        "log" to "txt",
        "doc" to "txt",
        "docx" to "txt",
        "rtf" to "txt",
        "pdf" to "pdf",
        "epub" to "pdf",
        "rst" to "rst",
        "adoc" to "rst",
        "tex" to "latex",
        "latex" to "latex",
        "bib" to "latex",
        "typ" to "latex",
        "ipynb" to "jupyter",

        // Build
        "mk" to "make",
        "cmake" to "make",
        "sln" to "build",
        "lock" to "lockfile",
        "map" to "sourcemap",

        // Media
        "png" to "image",
        "jpg" to "image",
        "jpeg" to "image",
        "gif" to "image",
        "bmp" to "image",
        "ico" to "image",
        "webp" to "image",
        "avif" to "image",
        "tiff" to "image",
        "psd" to "image",
        "ttf" to "font",
        "otf" to "font",
        "woff" to "font",
        "woff2" to "font",
        "eot" to "font",
        "mp3" to "audio",
        "wav" to "audio",
        "ogg" to "audio",
        "flac" to "audio",
        "aac" to "audio",
        "m4a" to "audio",
        "mp4" to "video",
        "avi" to "video",
        "mov" to "video",
        "mkv" to "video",
        "webm" to "video",
        "obj" to "3d",
        "fbx" to "3d",
        "gltf" to "3d",
        "glb" to "3d",
        "stl" to "3d",
        "blend" to "3d",

        // Archives
        "zip" to "archive",
        "tar" to "archive",
        "gz" to "archive",
        "7z" to "archive",
        "rar" to "archive",
        "tgz" to "archive",
        "bz2" to "archive",
        "xz" to "archive",
        "deb" to "archive",
        "rpm" to "archive",
        "dmg" to "archive",
        "iso" to "archive",

        // Security
        "pem" to "key",
        "cer" to "key",
        "cert" to "key",
        "crt" to "key",
        "pub" to "key",
        "gpg" to "key",
        "p12" to "key",
        "pfx" to "key",
        "keystore" to "key",
        "jks" to "key",

        // Git
        "gitignore" to "gitignore",
        "gitattributes" to "gitignore",
        "patch" to "gitignore",
        "diff" to "gitignore",

        // Test
        "feature" to "test",
        "snap" to "test",

        // Synced with VS Code/Zed mappings
        "shtml" to "html",
        "slim" to "html",
        "haml" to "html",
        "ndjson" to "json",
        "hjson" to "json",
        "tsbuildinfo" to "json",
        "gitmodules" to "gitignore",
        "nim" to "nim",
        "nims" to "nim",
        "gd" to "gdscript",
        "tscn" to "gdscript",
        "tres" to "gdscript",
        "ksh" to "shell",
        "csh" to "shell",
        "tif" to "image",
        "heic" to "image",
        "heif" to "image",
        "raw" to "image",
        "dng" to "image",
        "eps" to "image",
        "ai" to "image",
        "fsi" to "csharp",
        "plpgsql" to "sql",
        "xls" to "csv",
        "xlsx" to "csv",
        "ods" to "csv",
        "tfbackend" to "terraform",
        "odt" to "txt",
        "pptx" to "pdf",
        "ppt" to "pdf",
        "odp" to "pdf",
        "asciidoc" to "rst",
        "ttc" to "font",
        "fnt" to "font",
        "wma" to "audio",
        "opus" to "audio",
        "aiff" to "audio",
        "alac" to "audio",
        "m4p" to "audio",
        "wmv" to "video",
        "flv" to "video",
        "mpeg" to "video",
        "mpg" to "video",
        "m4v" to "video",
        "ogv" to "video",
        "arj" to "archive",
        "zst" to "archive",
        "lz" to "archive",
        "lzma" to "archive",
        "cab" to "archive",
        "img" to "archive",
        "apk" to "archive",
        "frag" to "wasm",
        "vert" to "wasm",
        "shader" to "wasm",
        "pgp" to "key",
        "asc" to "key",
        "sig" to "key",
        "sol" to "solidity",
        "http" to "http",
        "rest" to "http",
        "containerignore" to "docker",
    )

    val FOLDER_NAMES = mapOf(
        "src" to "folder-src-closed",
        "source" to "folder-src-closed",
        "lib" to "folder-lib-closed",
        "libs" to "folder-lib-closed",
        "vendor" to "folder-lib-closed",
        "packages" to "folder-lib-closed",
        "test" to "folder-tests-closed",
        "tests" to "folder-tests-closed",
        "__tests__" to "folder-tests-closed",
        "__test__" to "folder-tests-closed",
        "spec" to "folder-tests-closed",
        "specs" to "folder-tests-closed",
        "e2e" to "folder-tests-closed",
        "cypress" to "folder-tests-closed",
        "public" to "folder-public-closed",
        "static" to "folder-public-closed",
        "wwwroot" to "folder-public-closed",
        "assets" to "folder-assets-closed",
        "resources" to "folder-assets-closed",
        "res" to "folder-assets-closed",
        "media" to "folder-assets-closed",
        "images" to "folder-assets-closed",
        "img" to "folder-assets-closed",
        "config" to "folder-config-closed",
        "configs" to "folder-config-closed",
        "configuration" to "folder-config-closed",
        "settings" to "folder-config-closed",
        ".idea" to "folder-config-closed",
        ".gradle" to "folder-build-closed",
        ".intellijPlatform" to "folder-config-closed",
        "gradle" to "folder-config-closed",
        ".vscode" to "folder-config-closed",
        ".run" to "folder-config-closed",
        ".devcontainer" to "folder-docker-closed",
        ".git" to "folder-git-closed",
        ".github" to "folder-github-closed",
        "node_modules" to "folder-node-modules-closed",
        ".next" to "folder-build-closed",
        ".nuxt" to "folder-build-closed",
        ".svelte-kit" to "folder-build-closed",
        "dist" to "folder-build-closed",
        "build" to "folder-build-closed",
        "out" to "folder-build-closed",
        "output" to "folder-build-closed",
        "target" to "folder-build-closed",
        "bin" to "folder-build-closed",
        "scripts" to "folder-scripts-closed",
        "tools" to "folder-scripts-closed",
        "docs" to "folder-docs-closed",
        "doc" to "folder-docs-closed",
        "documentation" to "folder-docs-closed",
        "styles" to "folder-styles-closed",
        "style" to "folder-styles-closed",
        "css" to "folder-styles-closed",
        "scss" to "folder-styles-closed",
        "components" to "folder-components-closed",
        "component" to "folder-components-closed",
        "widgets" to "folder-components-closed",
        "ui" to "folder-components-closed",
        "hooks" to "folder-hooks-closed",
        "composables" to "folder-hooks-closed",
        "utils" to "folder-utils-closed",
        "util" to "folder-utils-closed",
        "helpers" to "folder-utils-closed",
        "common" to "folder-utils-closed",
        "shared" to "folder-utils-closed",
        "api" to "folder-api-closed",
        "apis" to "folder-api-closed",
        "routes" to "folder-api-closed",
        "endpoints" to "folder-api-closed",
        "db" to "folder-database-closed",
        "database" to "folder-database-closed",
        "migrations" to "folder-database-closed",
        "seeds" to "folder-database-closed",
        "prisma" to "folder-database-closed",
        "docker" to "folder-docker-closed",
        ".docker" to "folder-docker-closed",
        "pages" to "folder-pages-closed",
        "views" to "folder-pages-closed",
        "screens" to "folder-pages-closed",
        "layouts" to "folder-pages-closed",
        "app" to "folder-pages-closed",
        "types" to "folder-types-closed",
        "typings" to "folder-types-closed",
        "@types" to "folder-types-closed",
        "interfaces" to "folder-types-closed",

        // Synced with VS Code/Zed folder mappings
        ".cache" to "folder-build-closed",
        ".ci" to "folder-github-closed",
        ".config" to "folder-config-closed",
        ".cypress" to "folder-tests-closed",
        ".husky" to "folder-git-closed",
        ".netlify" to "folder-config-closed",
        ".storybook" to "folder-tests-closed",
        ".tmp" to "folder-build-closed",
        ".vercel" to "folder-config-closed",
        "__fixtures__" to "folder-tests-closed",
        "__mocks__" to "folder-tests-closed",
        "__snapshots__" to "folder-tests-closed",
        "addons" to "folder-lib-closed",
        "apps" to "folder-src-closed",
        "backend" to "folder-api-closed",
        "ci" to "folder-github-closed",
        "client" to "folder-src-closed",
        "constants" to "folder-config-closed",
        "content" to "folder-docs-closed",
        "controllers" to "folder-api-closed",
        "core" to "folder-lib-closed",
        "coverage" to "folder-tests-closed",
        "databases" to "folder-database-closed",
        "demo" to "folder-docs-closed",
        "drizzle" to "folder-database-closed",
        "entities" to "folder-types-closed",
        "example" to "folder-docs-closed",
        "examples" to "folder-docs-closed",
        "extensions" to "folder-lib-closed",
        "fixtures" to "folder-tests-closed",
        "fonts" to "folder-assets-closed",
        "frontend" to "folder-src-closed",
        "functions" to "folder-api-closed",
        "graphql" to "folder-api-closed",
        "handlers" to "folder-api-closed",
        "helper" to "folder-utils-closed",
        "i18n" to "folder-config-closed",
        "k8s" to "folder-docker-closed",
        "kubernetes" to "folder-docker-closed",
        "lambda" to "folder-api-closed",
        "lang" to "folder-config-closed",
        "less" to "folder-styles-closed",
        "locale" to "folder-config-closed",
        "locales" to "folder-config-closed",
        "middleware" to "folder-api-closed",
        "mocks" to "folder-tests-closed",
        "models" to "folder-types-closed",
        "modules" to "folder-lib-closed",
        "plugins" to "folder-lib-closed",
        "providers" to "folder-api-closed",
        "sass" to "folder-styles-closed",
        "schemas" to "folder-types-closed",
        "server" to "folder-api-closed",
        "services" to "folder-api-closed",
        "storybook" to "folder-tests-closed",
        "templates" to "folder-pages-closed",
        "tmp" to "folder-build-closed",
        "translations" to "folder-config-closed",
        "uploads" to "folder-assets-closed",
        "wiki" to "folder-docs-closed",
    )
}
